import 'package:magazine_luiza/models/product.dart';

List<Product> products = [
  Product(
    photo: "assets/images/celular.jpg",
    name: "Smartphone Samsung Galaxy A71 128GB Azul 6GB RAM",
    description: "Tela 6,7\" Câm. Quádrupla + Selfie 32MP",
    price: 2149.98,
    installments: 10,
    interestRate: 8,
    isFavorite: true,
  ),
  Product(
    photo: "assets/images/computador.jpg",
    name: "PC Gamer Neologic Start NLI81426 Ryzen 3 2200G 8GB",
    description: "Radeon Vega 8 Integrado + SSD 240GB",
    price: 5349.00,
    installments: 20,
    interestRate: 10,
    isFavorite: true,
  ),
  Product(
    photo: "assets/images/drone.jpg",
    name: "Drone Multilaser Eagle FPV",
    description: "Câmera HD Flips 360",
    price: 2000.00,
    installments: 7,
    interestRate: 0,
  ),
  Product(
    photo: "assets/images/fritadeira.jpg",
    name: "Fritadeira Elétrica sem Óleo/Air Fryer Nell Smart",
    description: "Peta 2,4L com Timer",
    price: 250.01,
    installments: 3,
    interestRate: 5,
  ),
  Product(
    photo: "assets/images/geladeira.jpg",
    name: "Geladeira Brastemp Fros Free Duplex Evox",
    description: "375L BRM45 HKANA",
    price: 2699.99,
    installments: 12,
    interestRate: 0,
    isFavorite: true,
  ),
  Product(
    photo: "assets/images/microfone.jpg",
    name: "Microfone de Mesa Condensador para Celular, Computador e Notebook",
    description: "Redshock",
    price: 101.01,
    installments: 2,
    interestRate: 0,
  ),
  Product(
    photo: "assets/images/ventilador.jpg",
    name: "Ventilador de Parede e Mesa Mondial Maxi Power",
    description: "NV-15-6P-FB 30cm 3 Velocidades",
    price: 95.59,
    installments: 3,
    interestRate: 5,
    isFavorite: true,
  ),
];